spring.application.name=Data-Champions

spring.datasource.url=jdbc:mysql://localhost:3306/datachampions?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1205
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

riot.api.key=RGAPI-b82f152b-eb43-43f0-8c91-5981f6e1ac4e